services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - internal

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        ports:
            - 8080:80
        env_file:
            - .env
        volumes:
            - pgadmin:/var/lib/pgadmin
        networks:
            - internal
        restart: always

    backend: 
        image: ghcr.io/${OWNER}/backend:latest
        container_name: backend
        build:
            context: backend
        env_file:
            - .env
        ports:
            - 3000:3000
        networks:
            - internal
        depends_on:
            - postgres

    frontend:
        image: ghcr.io/${OWNER}/frontend:latest
        container_name: frontend
        build:
            context: frontend
        volumes:
            - frontend:/app/dist
        env_file:
            - .env

    server:
        image: ghcr.io/${OWNER}/server:latest
        container_name: server
        build: 
            context: nginx
        ports:
            - 81:80
        volumes:
            - frontend:/var/www
        depends_on:
            - frontend
            - backend
        networks:
            - internal


volumes:
    pgadmin:
    db:
    frontend:

networks:
    internal: