name: Docker Image CI

on:
  push:
    branches: [ "main", "review" ]
  pull_request:
    branches: [ "main", "review" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions: 
      packages: write

    steps:
    - name: set lower case owner name
      run: echo "REPO=${OWNER,,}" >> $GITHUB_ENV
      env:
        OWNER: '${{ github.repository_owner }}'
    
    - run: echo "repo ${REPO}"

    - name: check repo
      uses: actions/checkout@v4

    - name: set up qemu
      uses: docker/setup-qemu-action@v3
    
    - name: set up buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Docker Hub login
      uses: docker/login-action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: build and push backend
      uses: docker/build-push-action@v6
      with: 
        context: '{{defaultContext}}:backend'
        push: true
        tags: 'ghcr.io/${{ env.REPO }}/backend:latest'
    
    - name: build and push frontend
      uses: docker/build-push-action@v6
      with: 
        context: '{{defaultContext}}:frontend'
        push: true
        tags: 'ghcr.io/${{ env.REPO }}/frontend:latest'

    - name: build and push server
      uses: docker/build-push-action@v6
      with: 
        context: '{{defaultContext}}:server'
        push: true
        tags: 'ghcr.io/${{ env.REPO }}/server:latest'
